In [1]:
import numpy as np

## Create and Read

#### 1D Array

In [2]:
arr1=np.array([1,2,3,4])
arr1

array([1, 2, 3, 4])

#### 2D Array

In [4]:
arr2=np.array([[1,4,6],[7,8,9]])
arr2

array([[1, 4, 6],
       [7, 8, 9]])

In [5]:
arr2.shape

(2, 3)

#### Update & Delete

In [6]:
a1=np.random.rand(2,3,2)
a2=np.random.rand(2,3,2)

In [7]:
a1

array([[[0.52322117, 0.93960154],
        [0.87891138, 0.04476925],
        [0.58226294, 0.26046165]],

       [[0.72518408, 0.56571115],
        [0.51795553, 0.49629894],
        [0.67346483, 0.42595256]]])

In [8]:
np.add(a1,a2)

array([[[1.34854272, 1.41819764],
        [1.17683867, 0.73585242],
        [1.43786147, 1.18933925]],

       [[0.87068706, 0.58920701],
        [0.83665299, 1.33939439],
        [1.50180784, 0.61457544]]])

In [9]:
mins=np.min(a1)
mins

np.float64(0.044769253280590116)